<?php
/**
 * Register a shortcode called 'ss_shortcode' with attributes.
 *
 * Usage: [ss_shortcode attribute="your_value"]Content goes here[/ss_shortcode]
 *
 * @param array  $atts    Shortcode attributes and their default values.
 * @param string $content The content inside the shortcode.
 *
 * @return string The HTML output generated by the shortcode.
 */

add_shortcode('ss_shortcode', 'ss_shortcode_callback');

function ss_shortcode_callback($atts, $content = null)
{
    // Set default attributes.
    $atts = shortcode_atts(
        array(
            'attribute' => 'default_value',
        ),
        $atts,
        'atts_shortcode'
    );

    // Generate the HTML output using attributes and content.
    $output = '<div class="' . esc_attr($atts['attribute']) . '">' . esc_html($content) . '</div>';

    return $output;
}
